<<<<<<< HEAD
# Generated by Django 2.2.7 on 2020-02-09 12:23
=======
# Generated by Django 3.0.2 on 2020-02-08 21:21
>>>>>>> f45427dd456a5fd7e4966996a9258963cde0d58b

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_game'),
=======
        ('shop', '0002_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> f45427dd456a5fd7e4966996a9258963cde0d58b
    ]

    operations = [
        migrations.CreateModel(
            name='GamePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_price', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highscore', models.PositiveIntegerField()),
                ('save_data', models.TextField()),
<<<<<<< HEAD
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('game_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='play_game.GamePurchase')),
>>>>>>> f45427dd456a5fd7e4966996a9258963cde0d58b
            ],
        ),
    ]
