# Generated by Django 3.0.2 on 2020-02-08 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_game'),
        ('play_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepurchase',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.Game'),
        ),
        migrations.AlterField(
            model_name='gamepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
