# Generated by Django 3.0.2 on 2020-02-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_allhighscores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play_game', '0002_auto_20200209_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='game_purchase',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
