# Generated by Django 3.0.2 on 2020-02-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0004_auto_20200210_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePurchase',
        ),
    ]
