# Generated by Django 3.0.2 on 2020-02-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0005_delete_gamepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='highscore',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='save_data',
            field=models.TextField(null=True),
        ),
    ]
