# Generated by Django 3.0.2 on 2020-02-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile')),
                ('seller_id', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
            bases=('users.profile',),
        ),
    ]
