# Generated by Django 3.0.2 on 2020-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
