# Generated by Django 3.0.2 on 2020-02-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_game_times_played'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllHighScores',
        ),
    ]
